spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utnphones?serverTimezone=UTC
    username: root
    password: pastrana
  jpa:
    properties:
      hibernate.format_sql: true


#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true